server:
  port: 40000
spring:
  application:
    name: gateway-service
  cloud:
    #网关配置
    gateway:
      #一组路由规则(数组)
      routes:
        # - 表示yml中的数组格式
        - id: test_route #路由唯一标识
          uri: http://www.baidu.com #路由转发目标地址 不是完整地址 只需要定位到哪个服务即可
          predicates: #断言规则 用于路由规则的匹配 就是条件的判断
            - Path=/test/** #只需要通过localhost:40000/test/xxx
                            #最终路由的地址： http://www.baidu.com/test
          filters: #过滤器
            - StripPrefix=1 #如果匹配上了 去掉一级前缀
#        - id:
#          uri:
#          predicates:
#          filters:
    nacos:
      server-add: 127.0.0.1:8848 #nacos服务端地址
      discovery:
        username: nacos #nacos账号
        password: nacos #nacos密码
        namespace: public #默认的命名空间
        ephemeral: true #是否是临时实例
